// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Prueba unitaria selenium', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Prueba unitaria selenium', async function() {
    await driver.get("http://localhost/Reto_Tecnico/NMPVal/frontend/")
    await driver.manage().window().setRect({ width: 1936, height: 1056 })
    await driver.findElement(By.css("html")).click()
    {
      const element = await driver.findElement(By.css("html"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css("html"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css("html"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css("html")).click()
    await driver.findElement(By.id("idMaterial")).click()
    await driver.findElement(By.id("idMaterial")).sendKeys("001")
    await driver.findElement(By.id("pesoGramos")).click()
    await driver.findElement(By.id("pesoGramos")).sendKeys("10")
    await driver.findElement(By.css("button")).click()
    await driver.findElement(By.id("idMaterial")).click()
    await driver.findElement(By.id("idMaterial")).sendKeys("002")
    await driver.findElement(By.css("button")).click()
    await driver.findElement(By.id("idMaterial")).click()
    await driver.findElement(By.id("idMaterial")).sendKeys("003")
    await driver.findElement(By.css("button")).click()
    await driver.findElement(By.id("idMaterial")).click()
    await driver.findElement(By.id("idMaterial")).sendKeys("004")
    await driver.findElement(By.id("pesoGramos")).click()
    await driver.findElement(By.id("pesoGramos")).sendKeys("15")
    await driver.findElement(By.css("button")).click()
    await driver.findElement(By.id("pesoGramos")).click()
    await driver.findElement(By.id("pesoGramos")).sendKeys("22.5")
    await driver.findElement(By.css("button")).click()
    await driver.findElement(By.id("idMaterial")).click()
    await driver.findElement(By.id("idMaterial")).sendKeys("005")
    await driver.findElement(By.css("button")).click()
    await driver.findElement(By.id("idMaterial")).click()
    await driver.findElement(By.id("idMaterial")).sendKeys("006")
    await driver.findElement(By.css("button")).click()
    await driver.findElement(By.id("idMaterial")).click()
    await driver.findElement(By.id("idMaterial")).sendKeys("007")
    await driver.findElement(By.css("button")).click()
    await driver.findElement(By.id("idMaterial")).click()
    await driver.findElement(By.id("idMaterial")).sendKeys("008")
    await driver.findElement(By.css("button")).click()
    await driver.findElement(By.id("idMaterial")).click()
    await driver.findElement(By.id("idMaterial")).sendKeys("007")
    await driver.findElement(By.id("idMaterial")).sendKeys(Key.ENTER)
    await driver.findElement(By.css("button")).click()
    await driver.findElement(By.id("idMaterial")).click()
    await driver.findElement(By.id("idMaterial")).sendKeys("006")
    await driver.findElement(By.css("button")).click()
    await driver.findElement(By.id("idMaterial")).click()
    await driver.findElement(By.id("idMaterial")).sendKeys("001")
    await driver.findElement(By.id("pesoGramos")).click()
    await driver.findElement(By.id("pesoGramos")).sendKeys("100")
    await driver.findElement(By.css("button")).click()
    await driver.findElement(By.id("montoPrestamo")).click()
  })
})
